package com.tinqinacademy.authentication.api.operations.changepasswordusingrecoverycode.operation;

import com.tinqinacademy.authentication.api.base.Operation;
import com.tinqinacademy.authentication.api.operations.changepasswordusingrecoverycode.input.ChangePasswordUsingRecoveryCodeInput;
import com.tinqinacademy.authentication.api.operations.changepasswordusingrecoverycode.output.ChangePasswordUsingRecoveryCodeOutput;

public interface ChangePasswordUsingRecoveryCodeOperation
    extends Operation<ChangePasswordUsingRecoveryCodeInput, ChangePasswordUsingRecoveryCodeOutput> {
}
